# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "azure", "~>0.7"
gem "azure-storage", "~>0.15.0.preview"
gem "hashie", "~>3.5"
gem "addressable", "~>2.5"

gem "paperclip", ">=4.3.6", :group => [:development, :test]
gem "sqlite3", "~>1.3.8", :group => [:development, :test]
gem "rspec", "~>3.0", :group => [:development, :test]
gem "simplecov", "~>0.16", :group => [:development, :test]
gem "activerecord", ">=4.2.0", :group => [:development, :test]
gem "activerecord-import", "~>0.19", :group => [:development, :test]
gem "activemodel", ">=4.2.0", :group => [:development, :test]
gem "activesupport", ">=4.2.0", :group => [:development, :test]
gem "hoe", ">=0", :group => [:development, :test]
gem "hoe-bundler", ">=0", :group => [:development, :test]
gem "hoe-gemspec", ">=0", :group => [:development, :test]
gem "hoe-git", ">=0", :group => [:development, :test]
gem "hoe-rubygems", ">=0", :group => [:development, :test]
gem "rdoc", ">=4.0", "<6", :group => [:development, :test]

# vim: syntax=ruby
